// AUTO-GENERATED by scripts/sync-syntax-ast-kinds.mjs — do not edit

import type { AstSyntaxFamily } from "./kinds.js";

export const SYNTAX_KINDS_BY_FAMILY = {
	Expression: ["ArrayLiteral", "Assign", "Binary", "Block", "Call", "CodeString", "EnumConstructor", "Grouped", "Index", "Lambda", "Literal", "MacroInvocation", "MacroMetavariable", "Match", "Member", "Path", "Spawn", "StructLiteral", "Try", "Unary"],
	Statement: ["Break", "Continue", "Expression", "For", "If", "Launch", "Let", "Return", "While", "With"],
	Item: ["AttributeDeclaration", "ContractDefinition", "EnumDefinition", "ExtendTypeDefinition", "Function", "HostDefinition", "InlineModule", "MacroDefinition", "Method", "ModuleDeclaration", "TestDefinition", "TypeDefinition", "UseDeclaration"],
	Type: ["Array", "Complex", "Primitive"],
} as const satisfies Record<AstSyntaxFamily, readonly string[]>;

export type SyntaxKindByFamily = {
	Expression: "ArrayLiteral" | "Assign" | "Binary" | "Block" | "Call" | "CodeString" | "EnumConstructor" | "Grouped" | "Index" | "Lambda" | "Literal" | "MacroInvocation" | "MacroMetavariable" | "Match" | "Member" | "Path" | "Spawn" | "StructLiteral" | "Try" | "Unary";
	Statement: "Break" | "Continue" | "Expression" | "For" | "If" | "Launch" | "Let" | "Return" | "While" | "With";
	Item: "AttributeDeclaration" | "ContractDefinition" | "EnumDefinition" | "ExtendTypeDefinition" | "Function" | "HostDefinition" | "InlineModule" | "MacroDefinition" | "Method" | "ModuleDeclaration" | "TestDefinition" | "TypeDefinition" | "UseDeclaration";
	Type: "Array" | "Complex" | "Primitive";
};

export function isSyntaxKindForFamily(family: AstSyntaxFamily, kind: string): boolean {
	return (SYNTAX_KINDS_BY_FAMILY[family] as readonly string[]).includes(kind);
}
